---
- name: Determine the right VNode num_token value 
  when: solr_enabled|int == 1
  set_fact: vnode_token_num={{ vnode_token_num_solr }}

#- debug: msg="{{ private_ip }}, {{ dc }}, {{ rack }}, {{ vnode }}, {{ vnode_token_num }}, {{ initial_token }}, {{ solr_enabled }}, {{ spark_enabled }}, {{ graph_enabled }}, {{ auto_bootstrap }}, {{ cluster_name }}, {{ data_file_directories }}, {{ commitlog_directory }}, {{ saved_caches_directory }}, {{ seeds }}"

- name: Configure DSE Analytics workload type
  when: spark_enabled|int == 1
  lineinfile:
    name: "{{ dse_default_dir }}/dse"
    regexp: '^SPARK_ENABLED='
    line: "SPARK_ENABLED=1"
    owner: cassandra
    group: cassandra
    mode: 0644

- name: Configure DSE Search workload type
  when: solr_enabled|int == 1
  lineinfile:
    name: "{{ dse_default_dir }}/dse"
    regexp: '^SOLR_ENABLED='
    line: "SOLR_ENABLED=1"
    owner: cassandra
    group: cassandra
    mode: 0644

- name: Configure DSE Graph workload type
  when: graph_enabled|int == 1 and dse_ver_major is version_compare('5.0', '>=')
  lineinfile:
    name: "{{ dse_default_dir }}/dse"
    regexp: '^GRAPH_ENABLED='
    line: "GRAPH_ENABLED=1"
    owner: cassandra
    group: cassandra
    mode: 0644

- name: Configure Cassandra VNode, if enabled 
  when: vnode|int == 1
  lineinfile:
    name: "{{ dse_config_dir }}/cassandra/cassandra.yaml"
    regexp: 'num_tokens\:'
    line: "num_tokens: {{ vnode_token_num }}"
    owner: cassandra
    group: cassandra
    mode: 0644

- name: Configure single-token value, if VNode is NOT enabled (cassandra.yaml)
  when: vnode|int == 0
  lineinfile:
    name: "{{ dse_config_dir }}/cassandra/cassandra.yaml"
    regexp: 'initial_token\:'
    line: "initial_token: {{ initial_token }}"
    owner: cassandra
    group: cassandra
    mode: 0644

- name: Create Cassandra directories for data, commitlog, saved_caches
  file:
    path: "{{ item }}"
    state: directory
    owner: cassandra
    group: cassandra
    mode: 0755
  with_items:
    - "{{ data_file_directories }}"
    - "{{ commitlog_directory }}"
    - "{{ saved_caches_directory }}"

- name: Create Cassandra directory for hitns and cdc_raw (only applicable to DSE 5.0+)
  when: dse_ver_major is version_compare('5.0', '>=') 
  file:
    path: "{{ item }}"
    state: directory
    owner: cassandra
    group: cassandra
    mode: 0755
  with_items:
    - "{{ hints_directory }}"
    - "{{ cdc_raw_directory }}"

- name: Create Cassandra directory for metadata (only applicable to DSE 6.8+)
  when: dse_ver_major is version_compare('6.8', '>=') 
  file:
    path: "{{ item }}"
    state: directory
    owner: cassandra
    group: cassandra
    mode: 0755
  with_items:
    - "{{ metadata_directory }}"

- name: Configure DSE cluster name, seeds list, endpoint_snitch, listen_address, commitlog_directory, saved_caches_directory, hints_directory, cdc_raw_directory (cassandra.yaml)
  when: dse_ver_major is version_compare('5.0', '>=')
  lineinfile:
    name: "{{ dse_config_dir }}/cassandra/cassandra.yaml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: cassandra
    group: cassandra
    mode: 0644
  with_items:
    - { regexp: 'cluster_name\:', line: "cluster_name: '{{ cluster_name }}'" }
    - { regexp: '- seeds\:', line: '          - seeds: "{{ seeds }}"' }
    - { regexp: 'endpoint_snitch\:', line: "endpoint_snitch: GossipingPropertyFileSnitch" }
    - { regexp: '^listen_address\:', line: "listen_address: {{ ansible_default_ipv4.address }}" }
    - { regexp: '^commitlog_directory\:', line: 'commitlog_directory: {{ commitlog_directory }}' }
    - { regexp: '^saved_caches_directory\:', line: 'saved_caches_directory: {{ saved_caches_directory }}' }
    - { regexp: '^hints_directory\:', line: 'hints_directory: {{ hints_directory }}' }
    - { regexp: '^cdc_raw_directory\:', line: 'cdc_raw_directory: {{ cdc_raw_directory }}' }
    - { regexp: 'allocate_tokens_for_local_replication_factor\:', line: 'allocate_tokens_for_local_replication_factor: 3' }

- name: Configure DSE rpc_address and broadcast_rpc_address (only applicable to 5.0 and 5.1)
  when: dse_ver_major is version_compare('5.0', '>=') and dse_ver_major is version_compare('6.0', '<') 
  lineinfile:
    name: "{{ dse_config_dir }}/cassandra/cassandra.yaml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: cassandra
    group: cassandra
    mode: 0644
  with_items:
    - { regexp: '^rpc_address\:', line: "rpc_address: {{ ansible_default_ipv4.address }}" }
#    - { regexp: '^rpc_address\:', line: "rpc_address: 0.0.0.0" }
#    - { regexp: '#*\s*broadcast_rpc_address\:', line: "broadcast_rpc_address: {{ ansible_default_ipv4.address }}" }

- name: Configure DSE native_transport_address and native_transport_broadcast_address (only applicable to 6.0+)
  when: dse_ver_major is version_compare('6.0', '>=')
  lineinfile:
    name: "{{ dse_config_dir }}/cassandra/cassandra.yaml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: cassandra
    group: cassandra
    mode: 0644
  with_items:
    - { regexp: '^native_transport_address\:', line: "native_transport_address: {{ ansible_default_ipv4.address }}" }
#    - { regexp: '^native_transport_address\:', line: "native_transport_address: 0.0.0.0" }
#    - { regexp: '#*\s*native_transport_broadcast_address\:', line: "native_transport_broadcast_address: {{ ansible_default_ipv4.address }}" }

- name: Configure DSE metadata_directory (cassandra.yaml), DSE 6.8+ only
  when: dse_ver_major is version_compare('6.8', '>=') 
  lineinfile:
    name: "{{ dse_config_dir }}/cassandra/cassandra.yaml"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: cassandra
    group: cassandra
    mode: 0644
  with_items:
    - { regexp: '^metadata_directory\:', line: 'metadata_directory: {{ metadata_directory }}' }

- name: Configure Cassandra data directory (cassandra.yaml)
  replace:
    name: "{{ dse_config_dir }}/cassandra/cassandra.yaml"
    regexp: "- /var/lib/cassandra/data"
    replace: "- {{ data_file_directories }}"
    owner: cassandra
    group: cassandra
    mode: 0644

- name: Configure DC and Rack settings (cassandra-rackdc.properties)
  lineinfile:
    name: "{{ dse_config_dir }}/cassandra/cassandra-rackdc.properties"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    owner: cassandra
    group: cassandra
    mode: 0644
  with_items:
    - { regexp: 'dc\=', line: 'dc={{ dc }}' }
    - { regexp: 'rack\=', line: 'rack={{ rack }}' }